#!/bin/bash
cd ~
tmux new-session -d "nvim"
tmux split-window -h
tmux send-keys 'cd .ratanrc && clear' Enter
tmux rename-window '.ratanrc'
tmux new-window -n stf
tmux send-keys 'cd stf && clear' Enter
tmux -2 attach-session -d
